Update Dockerfile.template
Fix download of wifi-connect (copied from https://github.com/balena-os/wifi-connect/blob/master/Dockerfile.template)

diff --git a/wifi-connect/Dockerfile.template b/wifi-connect/Dockerfile.template
--- a/wifi-connect/Dockerfile.template
+++ b/wifi-connect/Dockerfile.template
@@ -4,10 +4,25 @@ RUN install_packages dnsmasq wireless-tools git rsync binutils busybox-static
 
 WORKDIR /usr/src/app
 
-RUN curl https://api.github.com/repos/balena-io/wifi-connect/releases/latest -s \
-    | grep -hoP 'browser_download_url": "\K.*%%BALENA_ARCH%%\.tar\.gz' \
-    | xargs -n1 curl -Ls \
-    | tar -xvz -C /usr/src/app/
+RUN \
+    export BASE_URL="https://github.com/balena-os/wifi-connect/releases" &&\    
+    case $BALENA_ARCH in \
+        "aarch64") \
+            BINARY_ARCH_NAME="aarch64-unknown-linux-gnu" ;; \
+        "amd64") \
+            BINARY_ARCH_NAME="x86_64-unknown-linux-gnu" ;;\
+        "armv7hf") \
+            BINARY_ARCH_NAME="armv7-unknown-linux-gnueabihf" ;;\
+        *) \
+            echo >&2 "error: unsupported architecture ($BALENA_ARCH)"; exit 1 ;; \ 
+    esac;\
+    if [ ${VERSION} = "latest" ]; then \
+        export URL_PARTIAL="latest/download" ; \
+    else \
+        export URL_PARTIAL="download/${VERSION}" ; \
+    fi; \
+    curl -Ls "$BASE_URL/$URL_PARTIAL/wifi-connect-$BINARY_ARCH_NAME.tar.gz" \
+    | tar -xvz -C  /usr/src/app/
 
 RUN pip install git+https://github.com/larsks/dockerize
 
